# Generated by Django 3.2.25 on 2025-08-31 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        ("postgres_searchindex", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="indexentry",
            name="site_id",
        ),
        migrations.AddField(
            model_name="indexentry",
            name="site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sites.site",
            ),
        ),
    ]
