# Generated by Django 4.2.23 on 2025-09-01 08:38

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("postgres_searchindex", "0002_auto_20250831_0738"),
    ]

    operations = [
        migrations.AddField(
            model_name="indexentry",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                editable=False, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="indexentry",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="indexentry_search_vector_idx"
            ),
        ),
    ]
