
# for CI/github actions
passenv = DATABASE_URL

[tox]
envlist = py{39,310,311,312}-django{42}, py{311,312}-django{52}, py312-django52-coverage, pre-commit

[gh-actions]
python =
    3.9: py39
    3.10: py310
    3.11: py311
    3.12: py312

[testenv:pre-commit]
deps =
    pre-commit
commands = pre-commit run --all-files

[testenv:py39-django42-coverage]
allowlist_externals = echo
commands =
    # https://github.com/nedbat/coveragepy/issues/1272
    pip install coverage<6
    coverage erase
    coverage run ./manage.py test
    coverage report --include='postgres_searchindex*' --omit='*/tests/*' --omit='*/migrations/*'
    coverage html --include='postgres_searchindex*' --omit='*/tests/*' --omit='*/migrations/*'
    echo "opener htmlcov/index.html"

[testenv]
commands = python manage.py test
setenv =
    DJANGO_SETTINGS_MODULE=postgres_searchindex.tests.settings
    PYTHONPATH={toxinidir}
deps =
    django42: Django>=4.2,<4.3
    django52: Django>=5.2,<5.3
    django-cms==3.11.10
    coverage
    psycopg
    django-environ
