

[tox]
envlist = py{39,310,311,313}-django{42}-djangocms{3}, py{311,312}-django{52}-djangocms{3,4,5}, py312-django52-djangocms5-coverage, pre-commit

[gh-actions]
python =
    3.9: py39
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313

[testenv:pre-commit]
deps =
    pre-commit
commands = pre-commit run --all-files

[testenv:py312-django52-djangocms5-coverage]
allowlist_externals = echo
# for CI/github actions
passenv = DATABASE_URL
commands =
    # https://github.com/nedbat/coveragepy/issues/1272
    pip install coverage<6
    coverage erase
    coverage run ./manage.py test
    coverage report --include='postgres_searchindex*' --omit='*/tests/*' --omit='*/migrations/*'
    coverage html --include='postgres_searchindex*' --omit='*/tests/*' --omit='*/migrations/*'
    echo "opener htmlcov/index.html"

[testenv]
commands = python manage.py test
# for CI/github actions
passenv = DATABASE_URL
deps =
    django42: Django>=4.2,<4.3
    django52: Django>=5.2,<5.3
    djangocms3: django-cms==3.11.10
    djangocms4: django-cms==4.1.9
    djangocms5: django-cms==5.0.5
    coverage
    psycopg
    django-environ
