# Generated by Django 4.2.23 on 2026-01-18 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0022_auto_20180620_1551"),
        ("test_app", "0002_testmodel_published"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestPluginModel",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                ("field1", models.CharField(default="", max_length=64)),
                ("field_date", models.DateField(default=None, null=True)),
                ("field_datetime", models.DateTimeField(default=None, null=True)),
                ("field_time", models.TimeField(default=None, null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("cms.cmsplugin",),
        ),
    ]
